### ISSUE TITLE
Some little issues

### ISSUE THREAD

**Issue by JzMaple** [dbindel/sjtu-summer2018#2]
-  Lecture note of 2018-06-13, section 5 Bias-variance tradeoffs, there is a equation with a redundant bracket.  Here is the original text.

                Taking norm bounds, we find
               \[
                 \|A(\hat x - x)\| \leq \|A\| \|A_1^\dagger\| (\|e\| + \|r_1)\|),
               \]

-  Lecture note of 2018-06-14, section 8 Gradient descent, I think the condition that α < 1/λ_max should be changed to α < 2/λ_max. Because we should make the eigenvalues of I −αA in [0,1] to assure that e_k would be close to 0 after many rounds of iterations. That is to say |1 - αλ_i | < 1, for all i.  Therefore, the condition is α < 2/λ_max. What's more, if α < 1/λ_max, then α_* = 2/(λ_min + λ_max) does not satisfy the condition.

    Here is the original text.

                The iteration converges provided $\alpha < 1/\lambda_{\max}$, and the
                optimal $\alpha$ is
                \[
                  \alpha_* = \frac{2}{\lambda_{\min} + \lambda_{\max}},
                \]
                which leads to the spectral radius
                \[
                  1 - \frac{2 \lambda_{\min}}{\lambda_{\min} + \lambda_{\max}} =
                  1 - \frac{2}{1 + \kappa(A)}
                \]

**Comment by dbindel** [comment]
Thanks!  You're right on both counts, and I just pushed the appropriate corrections.
